/**
 * Shell SmartPay APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { StationLocatorController } from '../src';
import { testClient } from './testClient';
import { expectHeadersToMatch, makeApiCall } from './testHelper';

describe('StationLocatorController', () => {
  let controller : StationLocatorController;

  beforeAll(() => {
    controller = new StationLocatorController(testClient);
  });

  it('should Test StationlocatorV1StationsGetAroundLocation', async () => {
    const m = 'aroundLocation';

    const lon = 77.6730103;

    const lat = 12.9132169;

    const radius = 0.3;

    const response = await makeApiCall(
      () => controller.stationlocatorV1StationsGetAroundLocation(
        m,
        lon,
        lat,
        radius,
        undefined,
        undefined,
        undefined,
        undefined,
        undefined
      )
    );

    expect(response.statusCode).toBe(200);

    const expectedHeaders = { 'Content-Type': ['application/json', true] };

    expectHeadersToMatch(response.headers, expectedHeaders);
  });
});
