/**
 * Shell EVLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core';

/**
 * Creates an instance of MppAccesTokenErrorResponse
 */
interface MppAccesTokenErrorResponse {
  /** error code or short description */
  error: string;
  /** error code or short description due to invalid request or invalid client ID */
  error_code: string;
  /** Description of the error */
  error_description?: string;
}

export class MppAccesTokenErrorResponseError extends ApiError<MppAccesTokenErrorResponse> {}
