/**
 * Shell EVLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core';

/**
 * Creates an instance of PaymentEnablementErrorResponse
 */
interface PaymentEnablementErrorResponse {
  code?: number;
  message?: string;
}

export class PaymentEnablementErrorResponseError extends ApiError<PaymentEnablementErrorResponse> {}
