/**
 * Shell SmartPay APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core';

/**
 * Creates an instance of StationLocatorForbidden
 */
interface StationLocatorForbidden {
  errorCode?: string;
  errorDescription?: string;
}

export class StationLocatorForbiddenError extends ApiError<
  StationLocatorForbidden
> {}
