/**
 * Shell EVLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core';

/**
 * Creates an instance of StationLocatorNotFound
 */
interface StationLocatorNotFound {
  errorCode?: string;
  errorDescription?: string;
}

export class StationLocatorNotFoundError extends ApiError<StationLocatorNotFound> {}
