/**
 * Shell EVLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core';

/**
 * Creates an instance of StationLocatorUnauthorized
 */
interface StationLocatorUnauthorized {
  errorCode?: string;
  errorDescription?: string;
}

export class StationLocatorUnauthorizedError extends ApiError<StationLocatorUnauthorized> {}
