/**
 * Shell EVLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';

/** Object containing address details/elements */
export interface AroundLocationArrayDataItemsLoc {
  /** The station’s full street address, including building number */
  street?: string;
  /** The station’s postcode */
  pc?: string;
  /** The city the station is located within */
  city?: string;
  /** The region the station is located within */
  region?: string;
  /** The name of the country (in English) the station is located within */
  country: string;
  /** The two-letter ISO 3166 country code of the country the station is located within */
  ccode: string;
}

export const aroundLocationArrayDataItemsLocSchema: Schema<AroundLocationArrayDataItemsLoc> = object(
  {
    street: ['street', optional(string())],
    pc: ['pc', optional(string())],
    city: ['city', optional(string())],
    region: ['region', optional(string())],
    country: ['country', string()],
    ccode: ['ccode', string()],
  }
);
