/**
 * Shell EVLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';

export interface AroundLocationArrayDataItemsOpeningHoursItems {
  closingFromHours?: string;
  closingFromMinutes?: string;
  closingToHours?: string;
  closingToMinutes?: string;
  fromDay?: string;
  openingFromHours?: string;
  openingFromMinutes?: string;
  openingToHours?: string;
  openingToMinutes?: string;
  toDay?: string;
}

export const aroundLocationArrayDataItemsOpeningHoursItemsSchema: Schema<AroundLocationArrayDataItemsOpeningHoursItems> = object(
  {
    closingFromHours: ['Closing_From_Hours', optional(string())],
    closingFromMinutes: ['Closing_From_Minutes', optional(string())],
    closingToHours: ['Closing_To_Hours', optional(string())],
    closingToMinutes: ['Closing_To_Minutes', optional(string())],
    fromDay: ['From_Day', optional(string())],
    openingFromHours: ['Opening_From_Hours', optional(string())],
    openingFromMinutes: ['Opening_From_Minutes', optional(string())],
    openingToHours: ['Opening_To_Hours', optional(string())],
    openingToMinutes: ['Opening_To_Minutes', optional(string())],
    toDay: ['To_Day', optional(string())],
  }
);
