/**
 * Shell SmartPay APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, Schema, string } from '../schema';

export interface CollectingCompany {
  /** The ID of the Collecting Company (in GFN), also known as Shell Code of the selected payer. This property is mandatory if the ColCoCode code is not passed */
  colCoId: string;
}

export const collectingCompanySchema: Schema<CollectingCompany> = object({
  colCoId: ['ColCoId', string()],
});
