/**
 * Shell SmartPay APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';

export interface DeviceDetail {
  /** This is the mobile device’s unique ID (Vendor ID for iOS vs. Android ID for Android). This is only used for transactions made via the Shell Mobile App and will therefore be mandatory for requests originating from Shell’s mobile app but can be ignored by all other parties. */
  deviceId?: string;
  /** This is the mobile device’s model (machine name/systemInfo for iOS vs. Build.MODEL for Android).  This is only used for transactions made via the Shell Mobile App and will therefore be mandatory for requests originating from Shell’s mobile app but can be ignored by all other parties. */
  model?: string;
  /** This is the mobile device’s OS Version. This is only used for transactions made via the Shell Mobile App and will therefore be mandatory for requests originating from Shell’s mobile app but can be ignored by all other parties. */
  osVersion?: string;
  /**
   * This is only used for transactions made via Android versions of the Shell Mobile App and will therefore be mandatory for requests originating from Shell’s Android mobile app but can be ignored by all other devices and/or parties.
   * This field is used to capture the Shell App build that was used to make this call.
   */
  otherDeviceInformation?: string;
}

export const deviceDetailSchema: Schema<DeviceDetail> = object({
  deviceId: ['deviceId', optional(string())],
  model: ['model', optional(string())],
  osVersion: ['osVersion', optional(string())],
  otherDeviceInformation: ['otherDeviceInformation', optional(string())],
});
