/**
 * Shell EVLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';

export interface FaultResponseFaultDetail {
  /** The error code. */
  errorcode?: string;
}

export const faultResponseFaultDetailSchema: Schema<FaultResponseFaultDetail> = object(
  { errorcode: ['errorcode', optional(string())] }
);
