/**
 * Shell EVLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema, string } from '../schema';
import {
  FaultResponseFaultDetail,
  faultResponseFaultDetailSchema,
} from './faultResponseFaultDetail';

export interface FaultResponseFault {
  /** The description of the error. */
  faultstring?: string;
  detail?: FaultResponseFaultDetail;
}

export const faultResponseFaultSchema: Schema<FaultResponseFault> = object({
  faultstring: ['faultstring', optional(string())],
  detail: ['detail', optional(lazy(() => faultResponseFaultDetailSchema))],
});
