/**
 * Shell EVLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { number, object, optional, Schema, string } from '../schema';

export interface FinaliseFuelingRequestProductsItems {
  productId?: string;
  productName?: string;
  unitPrice?: number;
}

export const finaliseFuelingRequestProductsItemsSchema: Schema<FinaliseFuelingRequestProductsItems> = object(
  {
    productId: ['productId', optional(string())],
    productName: ['productName', optional(string())],
    unitPrice: ['unitPrice', optional(number())],
  }
);
