/**
 * Shell SmartPay APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  bigint,
  lazy,
  number,
  object,
  optional,
  Schema,
  string,
} from '../schema';
import { Payment, paymentSchema } from './payment';
import { Product, productSchema } from './product';

export interface FinaliseFuelingRequest {
  siteName?: string;
  timestamp?: bigint;
  volumeQuantity?: number;
  volumeUnit?: string;
  finalPrice?: number;
  currency?: string;
  status?: string;
  siteAddress?: string;
  originalPrice?: number;
  discount?: number;
  payment?: Payment;
  products?: Product[];
  mppTransactionId?: string;
}

export const finaliseFuelingRequestSchema: Schema<FinaliseFuelingRequest> = object(
  {
    siteName: ['siteName', optional(string())],
    timestamp: ['timestamp', optional(bigint())],
    volumeQuantity: ['volumeQuantity', optional(number())],
    volumeUnit: ['volumeUnit', optional(string())],
    finalPrice: ['finalPrice', optional(number())],
    currency: ['currency', optional(string())],
    status: ['status', optional(string())],
    siteAddress: ['siteAddress', optional(string())],
    originalPrice: ['originalPrice', optional(number())],
    discount: ['discount', optional(number())],
    payment: ['payment', optional(lazy(() => paymentSchema))],
    products: ['products', optional(array(lazy(() => productSchema)))],
    mppTransactionId: ['mppTransactionId', optional(string())],
  }
);
