/**
 * Shell EVLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, Schema, string } from '../schema';

export interface LoyaltyDetails {
  /** The user’s Loyalty card number. Although this is optional the expectation is that if this is specified then loyaltyType must also be specified */
  loyaltyId: string;
  /** Loyalty type being used, associated to the loyalty ID being passed. Possible values are 'Shell' */
  loyaltyType: string;
}

export const loyaltyDetailsSchema: Schema<LoyaltyDetails> = object({
  loyaltyId: ['loyaltyId', string()],
  loyaltyType: ['loyaltyType', string()],
});
