/**
 * Shell SmartPay APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { bigint, object, optional, Schema, string } from '../schema';

export interface MppAccesTokenResponse {
  /** It is the token used in the requests that required to authenticate an user. */
  accessToken?: string;
  /** type of token provided */
  tokenType?: string;
  /** validity of the access token in seconds */
  expiresIn?: bigint;
  /** scope for the authentication protocol */
  scope?: string;
}

export const mppAccesTokenResponseSchema: Schema<MppAccesTokenResponse> = object(
  {
    accessToken: ['access_token', optional(string())],
    tokenType: ['token_type', optional(string())],
    expiresIn: ['expires_in', optional(bigint())],
    scope: ['scope', optional(string())],
  }
);
