/**
 * Shell EVLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, Schema, string } from '../schema';

export interface PartnerTokenRequestBody {
  /** In OAuth 2.0, the term grant typee refers to the way an application gets an access token. OAuth 2.0 defines several grant types, including the authorization code flow. */
  grantType: string;
  /** After registering your app, you will receive a client ID and a client secret. The client ID is considered public information, and is used to build login URLs, or included in Javascript source code on a page. */
  clientId: string;
  /** After registering your app, you will receive a client ID and a client secret. The client ID is considered public information, and is used to build login URLs, or included in Javascript source code on a page. The client secret must be kept confidential. */
  clientSecret: string;
}

export const partnerTokenRequestBodySchema: Schema<PartnerTokenRequestBody> = object(
  {
    grantType: ['grant_type', string()],
    clientId: ['client_id', string()],
    clientSecret: ['client_secret', string()],
  }
);
