/**
 * Shell SmartPay APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema, string } from '../schema';
import {
  PaymentProperties,
  paymentPropertiesSchema,
} from './paymentProperties';

/** Object containing Payment details */
export interface PaymentDetails {
  /**
   * The type of commercial transaction. Permitted value\:
   *  *  B2B
   */
  paymentCategory?: string;
  /**
   * The payment method used to make the transaction. Possible values include:
   *   *  euroShell
   */
  paymentMethodId: string;
  /**
   * Object containing Payment Property details Please note:
   *    All the attributes are optional as they serve all payment methods (i.e. different payment methods require different fields to be filled/mandated). As a result, some of these fields will be mandatory depending on the selected payment method and the API will return an error if they are not completed
   */
  paymentProperties: PaymentProperties;
}

export const paymentDetailsSchema: Schema<PaymentDetails> = object({
  paymentCategory: ['paymentCategory', optional(string())],
  paymentMethodId: ['paymentMethodId', string()],
  paymentProperties: ['paymentProperties', lazy(() => paymentPropertiesSchema)],
});
