/**
 * Shell SmartPay APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  lazy,
  number,
  object,
  optional,
  Schema,
  string,
} from '../schema';
import { DeviceDetail, deviceDetailSchema } from './deviceDetail';
import { LoyaltyDetails, loyaltyDetailsSchema } from './loyaltyDetails';
import { PaymentDetails, paymentDetailsSchema } from './paymentDetails';

export interface PrepareFuelingRequest {
  /** The user’s current latitude */
  latitude: number;
  /** The user’s current longitude */
  longitude: number;
  /** The maximum fuelling amount that can be purchased. If the prepare fuelling is successful and the Customer starts fuelling their car, the pump will cut off once this threshold is reached. For B2B customers a maximum ceiling is set against their Shell Card. As a result, this can be left blank for B2B customers. If a value is provided it cannot be zero or lower and values that exceed ceiling will be ignored. */
  maximumFuelingAmount?: number;
  /** Expectation is that a user has to be located at a Shell petrol station in order to make this call. A user is recognised as being located at a Shell station if the user’s current location (as determined by GPS) is within 300 meters of a Shell station. Expectation is that requester will have established the Shell petrol station the user is located at prior to making this call by calling Station Locator APIs. The API will use stationId and siteCountry/GPS to verify the user is The user’s current latitude genuinely located at the specified Station. ‘mpp_station_id’ of the Station Locator API should be used. Leading ‘0’ should be dropped and only last four digits, should be used. E.G. for ‘00123’, only ‘0123’ should be used and for ‘04567’ only ‘4567’ should be used. */
  stationId: string;
  /** A two digit numeric number of the pump as marked on the forecourt (e.g. pump number 12) */
  pumpId: string;
  /** Object containing Loyalty details */
  loyaltyDetails?: LoyaltyDetails[];
  /**
   * The ID of the source application making this call. Each 3rd Party will be issued with its own sourceApp ID that must be specified correctly here
   *  *   3rdParty_App_Archetype
   */
  sourceApplication: string;
  /**
   * The type of device making this call. Permitted values for deviceType:
   *  *  car
   *  *  phone
   */
  deviceType?: string;
  /** Object containing Payment details */
  paymentDetails: PaymentDetails;
  /** Object containing device details */
  deviceDetails?: DeviceDetail[];
}

export const prepareFuelingRequestSchema: Schema<PrepareFuelingRequest> = object(
  {
    latitude: ['latitude', number()],
    longitude: ['longitude', number()],
    maximumFuelingAmount: ['maximumFuelingAmount', optional(number())],
    stationId: ['stationId', string()],
    pumpId: ['pumpId', string()],
    loyaltyDetails: [
      'loyaltyDetails',
      optional(array(lazy(() => loyaltyDetailsSchema))),
    ],
    sourceApplication: ['sourceApplication', string()],
    deviceType: ['deviceType', optional(string())],
    paymentDetails: ['paymentDetails', lazy(() => paymentDetailsSchema)],
    deviceDetails: [
      'deviceDetails',
      optional(array(lazy(() => deviceDetailSchema))),
    ],
  }
);
