/**
 * Shell EVLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, object, optional, Schema, string } from '../schema';

/** The response of prepare fueling returns */
export interface PrepareFuelingResponse {
  /** The unique identifier of the Order. NB at this stage the Customer hasn’t actually bought anything so there’s no formal transaction associated with the Order. A transaction is not processed until refuelling has been completed successfully and will be triggered by returning the nozzle to the pump. */
  mppTransactionId: string;
  /** An array of Strings that contain the list of products that the user can purchase at the specified Station/Pump. The text is localized based on the country. */
  products?: string[];
}

export const prepareFuelingResponseSchema: Schema<PrepareFuelingResponse> = object(
  {
    mppTransactionId: ['mppTransactionId', string()],
    products: ['products', optional(array(string()))],
  }
);
