/**
 * Shell SmartPay APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { number, object, optional, Schema, string } from '../schema';

export interface Product {
  productId?: string;
  productName?: string;
  unitPrice?: number;
}

export const productSchema: Schema<Product> = object({
  productId: ['productId', optional(string())],
  productName: ['productName', optional(string())],
  unitPrice: ['unitPrice', optional(number())],
});
